Add basic template contents
SantanderInnerSource/innersource-project-template pull request #1
Opened 2021-05-20 16:22 UTC by alpgarcia

First version of the main template documents.

The main goal is having a template and an example at the same time, so please have that in mind while reviewing and look for inconsistencies or aspects that should be remarked.

Thanks!

2021-05-20 17:00 UTC, dicortazar requested changes

2021-05-20 17:00 UTC, dicortazar commented on doc/governance.md
> +| Forums or Chat Platform​ | Microsoft Teams​ |
We could add Slack, Mattermost, Rocketchat as options.

2021-05-20 17:00 UTC, dicortazar commented on doc/governance.md
> +| Projects single entry point​ | Portal in Microsoft Teams​ |
We could link to other options as the SAP open source solution for portals and discoverability.

2021-05-20 17:00 UTC, dicortazar commented on doc/governance.md
> +| Announcements and news​ | Portal in Microsoft Teams <br /> Microsoft Teams channel​ |
Again too specific. We should go and detail others.

2021-05-21 06:37 UTC, alpgarcia commented on doc/governance.md
> +| Trusted Committer  | Daniel Izquierdo<br />Alberto Pérez<br />Jesús Alonso  | Is the Host Team. Responsible for both building the house and setting the house rules to ensure their guests are comfor
I did it at first, but thinking it twice, this project has also TCs and should be listed for anyone willing to contribute.

2021-05-21 06:40 UTC, alpgarcia commented on doc/governance.md
> +Project Board​ | Project​ | Management / Technical​ | Domain Leader<br />Trusted Committer<br />Champion<br />Technical expert | Ad hoc |​
I had sworn I changed this...

2021-05-21 06:43 UTC, alpgarcia commented on doc/governance.md
> +| Issues Tracker​ | JIRA Software by Atlassian (SaaS) <br />GitHub Issues​ |
Well, these are just some examples not a complete list of options, I just copied them from another project.

2021-05-21 06:44 UTC, alpgarcia commented on doc/governance.md
> +| Announcements and news​ | Portal in Microsoft Teams <br /> Microsoft Teams channel​ |
We can use others, but I don't want to list options here but provide an example of how a project would look like.

2021-05-21 06:56 UTC, alpgarcia commented
Thanks for the review @dicortazar!

I've addressed your comments in a new comment and also discussed some of your proposals above.

2021-05-21 07:04 UTC, dicortazar commented
This works for me, thanks a lot @alpgarcia !

2021-05-21 07:05 UTC, merged