Typos, clear corrections and minor improvements.
SantanderInnerSource/innersource-project-template pull request #2
Opened 2021-09-01 15:42 UTC by fioddor

* layout: This file would definitively benefit from **links** to "First contributions" and "Review process" documents, as these are its leading and trailing documents in the logical reading sequence. The latter is hidden/buried in the "Branch policy" and deserves a more prominent display.
* visuals: The **remark** to the author should be marked in italic for consistency. 
* typo: In "Sending the pull requests for review with any prior communication" "with" should be "with**out**".
* typo: **Align** branch name with text. Currently text says `main` and picture displays `master`.
* msg: Instead of "Go to GitHub. Create the Pull Request" I suggest "Go to **your fork** in GitHub and request the (assigned) upstream TC's to pull your changes". Users new to git/github/gitlab use to have a fuzzy understanding of what a pull/merge request is and believe it is some special kind of branch.
* msg: The possibilities explained in "could be useful for code repositories" don't apply to this project due to **size**, not because they are code-specific. In big non-code projects like critical documentation ones they could apply.
* typo: "git flow" -> "**Gitflow**"
* msg: https://www.atlassian.com/git/tutorials/comparing-workflows might be a good external **reference**.

2021-09-01 15:46 UTC, fioddor commented
Once in main, another PR is needed to send the changes upstream (and thereby test and showcase the fork-based workflow).

2021-09-02 16:54 UTC, alpgarcia requested changes
The only change I requested is to keep using `main`. It is better to update the picture (we can open an issue to not forget) as the actual branch name is `main`.

2021-09-02 16:54 UTC, alpgarcia commented on CONTRIBUTING.md
> +By following these ideas, the project `master` branch is the place to go to get the latest changes. Some of them could be still under testing processes. This means `master` is as stable as the testin
GitHub now uses `main` by default and so does this project.

2021-09-02 16:54 UTC, alpgarcia commented on CONTRIBUTING.md
> +  * In case of a bug, it will be fixed on the current `master` branch and not backported. **Users are expected to be always in the latest release**, supporting several versions at a time is currently
Same as above.

2021-09-03 12:11 UTC, alpgarcia approved these changes
LGTM, thanks!

2021-09-03 12:14 UTC, closed without merging