Add Code Review process
SantanderInnerSource/innersource-project-template pull request #3
Opened 2021-05-27 13:42 UTC by alpgarcia

Add code review process to the templates, linked from the README file.

2021-05-28 07:58 UTC, dicortazar requested changes
Thanks for this! Main discussion is related to the use of author vs committer.

2021-05-28 07:58 UTC, dicortazar commented on doc/code-review-process.md
> +  * **Committer**
Typically the committer is the person "committing" the piece of code to the main branch. In Git terminology there are two roles: the author and the committer. I'd suggest using "Author" instead of "Committer".

Depending on the piece of infrastructure used by the project, the committer may be the person that review the piece of code and then merge the code. In some other cases a bot is the one committing this (as the review process is done in other places). In other cases there is another commit for the merge, and others :).

2021-05-28 07:58 UTC, dicortazar commented on doc/code-review-process.md
> +    * Contributors have only read access to upstream repositories unless they are Trusted Committers and act as reviewers in the process. If they act as committers, they will just use their read perm
If we follow the previous definition of Author, then committer => author

2021-05-28 07:58 UTC, dicortazar commented on doc/code-review-process.md
> +    * The project code itself. All builds must be done from this copy (any of their branches or tags).
I'm afraid I don't get what you mean by "The project code itself".

2021-05-28 13:26 UTC, alpgarcia commented on doc/code-review-process.md
> +  * **Committer**
Agree!

2021-05-28 13:28 UTC, alpgarcia commented on doc/code-review-process.md
> +    * Contributors have only read access to upstream repositories unless they are Trusted Committers and act as reviewers in the process. If they act as committers, they will just use their read perm
Changed!

2021-05-28 13:32 UTC, alpgarcia commented on doc/code-review-process.md
> +    * The project code itself. All builds must be done from this copy (any of their branches or tags).
I've changed the text to better reflect what I mean.

2021-05-28 13:42 UTC, alpgarcia commented
Thanks @dicortazar, I've addressed your comments in a new fixup commit for you to review. Let me know if you want me to rebase it before merging.

2021-05-31 07:02 UTC, dicortazar commented
Looks good to me. I'll work on the rebase no worries.

Thanks!

2021-05-31 07:11 UTC, dicortazar commented
Already merged.

2021-05-31 07:11 UTC, closed without merging