More details for the making of changes.
SantanderInnerSource/innersource-project-template pull request #5
Opened 2021-06-08 14:20 UTC by fioddor

+ The play between remotes (upstream and origin) and local clone wasn't clear enough for newcomers.
+ Code review part reworded. The numbers were misleading: contributor was single and reviewers plural, but then the branch was referred as '_theirs_'.

2021-06-14 13:23 UTC, dicortazar requested changes

2021-06-14 13:23 UTC, dicortazar commented on CONTRIBUTING.md
> +* Set your branch (`git checkout <branch_name>`).
I think you're missing the -b option

2021-06-14 13:24 UTC, dicortazar commented
@fioddor, please check a minor comment, and then rebase everything into a single patch. Thanks!

2021-06-15 16:10 UTC, fioddor commented on CONTRIBUTING.md
> +* Set your branch (`git checkout <branch_name>`).
Corrected and squashed into single commit.

2021-06-16 09:05 UTC, dicortazar commented
LGTM, thanks!

2021-06-16 09:06 UTC, merged