Welcome pack.
SantanderInnerSource/innersource-project-template pull request #7
Opened 2021-06-30 16:54 UTC by fioddor

The existing files should serve as welcome pack for newcomers, because that's basically their job! We just need to re-arrange them to meet the requirements.

So this is what I did:
* README.md
  + More basic content:
    + people to contact and basic communication channels,
    + external documentation and resources from outside the repository,
    + section on how to use the software (previously just a link)
  + Re-arrange the repository documentation at 2 levels: plain usage vs. contribution.
* INSTALL.md
  + Consider (add) the use case of an existing repository.

2021-07-01 08:30 UTC, alpgarcia requested changes
Well, my personal idea of a welcome pack is a bit different. On the one hand, the README file would be more oriented to users than contributors, that is explaining the project itself, its structure, where to find the different pieces of information, and how to get started using it. As examples you can check: 
* Rust project: https://github.com/rust-lang/rust
* Atom: https://github.com/atom/atom
* NodeJS: https://github.com/nodejs/node
* Django: https://github.com/django/django
* Homebrew: https://github.com/Homebrew/brew

On the other hand, the idea I have for a welcome pack, what I'd like to find is a document guiding me, as a contributor, from scratch to my first contribution. That document should include links to documentation, tools (and how to install them), books I should read, etc. In the specific case of this project, I would assume that a contributor needs to understand what InnerSource is, so a first step could be suggesting some books and papers about the topic. Then, I'll make clear (as I tried to do in this review :)) what this project is: a template project that at the same time works for the project itself. And finally, I'd explain the type of contributors that could be sent and how to do it. Of course, we should point to the existing documents instead of rewriting stuff here and there (for instance, linking the CONTRIBUTING.md when talking about how to send a contribution to the project.

So, summarizing, I would expect a clear path for a contributor starting from scratch that covers, at least and not necessarily in this order:
* Pointers to the project documentation
* Pointers to support, people and/or communication channels (chats, forums, teams, ...)
* Suggested readings.
* Tools that need to install (if any).
* Everything should be ordered, so the newcomers know where to start (probably reading, installing stuff, looking for good first issue issues, etc.).

2021-07-01 08:30 UTC, alpgarcia commented on README.md
> +## Get in touch
I'd move this to the end of the page. Here it is hiding relevant information about the project itself. It should describe the actual ways of contacting us, the people in charge of reviewing contributions, remember this is a template, but it is also the README file of this specific project.

2021-07-01 08:30 UTC, alpgarcia commented on README.md
> +## Get in touch
Of course we can add other examples if needed, but making clear those are examples and doesn't work for this project.

2021-07-01 08:30 UTC, alpgarcia commented on README.md
> +## Read the docs
Imho, this title hides project contents as it seems these are documents for reading, in this case, these are the actual project contents, though. These are the rest of templates because everything in this repository should be templates which contents apply to the project itself.

2021-07-01 08:30 UTC, alpgarcia commented on README.md
> +### External must-reads
This should point to actual resources. In our case, this section could be part of the welcome pack (getting started with InnerSource project or any other title we may find interesting in the case of our project).

2021-07-01 08:30 UTC, alpgarcia commented on README.md
> +### Suggested readings
Same as before.

2021-07-01 08:30 UTC, alpgarcia commented on README.md
> +## Using this software/project
This should be on top, after the description of the project (I didn't add it to the README because there was a link to the INSTALL.md file)

2021-07-02 09:56 UTC, fioddor commented on README.md
> +## Get in touch
- [x] Substitute generic examples with the applied ones for this template project.

The best place for template usage directions is the beginning of each section, but since this is the fist one ever, the reader needs the context first (needs to know that this is both the template and the example).

2021-07-02 14:48 UTC, alpgarcia commented on README.md
> +## Get in touch
To make it clear, because GitHub is highlighting 3 lines here, I just referred to the last one, `Get in touch` section.

2021-07-02 15:36 UTC, alpgarcia requested changes
I have added a set of minor changes. Please @fioddor have a look at them.

2021-07-02 15:36 UTC, alpgarcia commented on doc/your-first-contributions.md
> +First off, please, feel wery welcome. We love external contributions!
`wery` -> `very`

2021-07-02 15:36 UTC, alpgarcia commented on doc/your-first-contributions.md
> +The usual path starts getting acquainted with the project, then finding a suitable task to juno into.
`juno` -> `jump`

2021-07-02 15:36 UTC, alpgarcia commented on doc/your-first-contributions.md
> +As newcomer you have a fresh view that the people envolved have most likely lost.
`envolved` -> `involved`

2021-07-02 15:36 UTC, alpgarcia commented on doc/your-first-contributions.md
> +  * Be spefic about the sypthoms. Provide a step by step procedure to reproduce the failure
`sypthoms` -> `symptoms`

2021-07-02 15:36 UTC, alpgarcia commented on doc/your-first-contributions.md
> +  * Follow up your request
missing a period at the end ;)

2021-07-02 15:36 UTC, alpgarcia commented on doc/your-first-contributions.md
> +  * Aviod ambigüity
`ambiguity`

2021-07-02 15:36 UTC, alpgarcia commented on doc/your-first-contributions.md
> +  * It is a good practice to use the userstory-mantra: As (profile) y want (proposal) in order to (purpose).
`I`

2021-07-02 15:36 UTC, alpgarcia commented on doc/your-first-contributions.md
> +    Be careful sepparating your purpose from your proposal.
`separating`

2021-07-02 15:36 UTC, alpgarcia commented on doc/your-first-contributions.md
> +  * *If it belongs outside the repository (videos, docs in a library, web stuff, ...) the process will be very different.
double asterisk

2021-07-02 15:36 UTC, alpgarcia commented on doc/your-first-contributions.md
> +* TDD:
I wouldn't use acronyms without defining them first. We shouldn't assume any background knowledge.

2021-07-02 15:36 UTC, alpgarcia commented on doc/your-first-contributions.md
> +  coded in [markdown](https://guides.github.com/features/mastering-markdown/) standard supported by Github and many other application.
`applications`

2021-07-05 09:25 UTC, fioddor commented on doc/your-first-contributions.md
> +  * *If it belongs outside the repository (videos, docs in a library, web stuff, ...) the process will be very different.
Its not a double one: The first is a bullet and the second one is an italic mark, as it is a note o how to use the template, not part of the example.

2021-07-05 13:52 UTC, alpgarcia approved these changes
LGTM, thanks @fioddor!

2021-07-05 13:54 UTC, merged